server:
  port: 8088
  servlet:
    context-path: /security
spring:
#  security:
#    user:
#      name: jilinwula
#      password: jilinwula.com
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security?useSSL=false&characterEncoding=utf8
    username: root
    password: jilinwula
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true